
// 10 - Se crea el archivo y se agrega el primer ENDPOINT de prueba,
//      este es el de consulta general de los datos usando el verbo GET de http

###
GET http://localhost:9000/Piezas HTTP/1.1

###

POST http://localhost:9000/Piezas HTTP/1.1
Content-Type: application/json

{
    "nombre_pieza":"Rimac-Nevera",
    "categoria_Pieza":1,
    "valorCompra_Pieza":15500,
    "fechaCompra_Pieza":"2023-12-30"
}

###

DELETE http://localhost:9000/Piezas/2 HTTP/1.1

###

PUT http://localhost:9000/Piezas/2 HTTP/1.1
Content-Type: application/json

{
    "nombre_pieza":"62 Corvette",
    "categoria_Pieza":1,
    "valorCompra_Pieza":14500,
    "fechaCompra_Pieza":"2023-12-30"
}